package kalkulator;


import java.awt.Color;
import java.awt.Label;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * 
 * @author HP
 */
public class KalkulatorKonversiOct extends javax.swing.JFrame{

    String display = "";
    double angka;
    int pilih;
    /**
     * Creates new form kelpbo
     */

    public KalkulatorKonversiOct(String title) {
        super(title);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KalkulatorPanel = new javax.swing.JPanel();
        displayBox = new javax.swing.JTextField();
        buttC = new javax.swing.JButton();
        butt7 = new javax.swing.JButton();
        butt4 = new javax.swing.JButton();
        butt1 = new javax.swing.JButton();
        buttMod = new javax.swing.JButton();
        butt8 = new javax.swing.JButton();
        butt5 = new javax.swing.JButton();
        butt2 = new javax.swing.JButton();
        butt9 = new javax.swing.JButton();
        butt6 = new javax.swing.JButton();
        butt3 = new javax.swing.JButton();
        buttKurAwal = new javax.swing.JButton();
        buttX = new javax.swing.JButton();
        butMin = new javax.swing.JButton();
        buttPlus = new javax.swing.JButton();
        buttPoint = new javax.swing.JButton();
        butt0 = new javax.swing.JButton();
        buttEval = new javax.swing.JButton();
        buttKurAkhir = new javax.swing.JButton();
        displayInnerBox = new javax.swing.JTextField();
        buttMR = new javax.swing.JButton();
        buttMC = new javax.swing.JButton();
        buttMPlus = new javax.swing.JButton();
        buttMMin = new javax.swing.JButton();
        buttPlusOrMin = new javax.swing.JButton();
        buttDegRad = new javax.swing.JButton();
        buttBagi = new javax.swing.JButton();
        buttPecahan = new javax.swing.JButton();
        buttAkar = new javax.swing.JButton();
        buttFaktorial = new javax.swing.JButton();
        buttPangkatY = new javax.swing.JButton();
        pilihanKonversi = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        buttSin = new javax.swing.JButton();
        buttCos = new javax.swing.JButton();
        buttTan = new javax.swing.JButton();
        butCosec = new javax.swing.JButton();
        buttSec = new javax.swing.JButton();
        buttCot = new javax.swing.JButton();
        buttExp = new javax.swing.JButton();
        buttLog = new javax.swing.JButton();
        displayMemoryBox = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        itemKalkulator = new javax.swing.JMenuItem();
        itemKonversi = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        menuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        KalkulatorPanel.setEnabled(false);

        displayBox.setEditable(false);
        displayBox.setBackground(new java.awt.Color(255, 255, 255));
        displayBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        displayBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        displayBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        displayBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBoxActionPerformed(evt);
            }
        });

        buttC.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttC.setText("AC/C");
        buttC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttCActionPerformed(evt);
            }
        });

        butt7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        butt7.setText("7");
        butt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt7ActionPerformed(evt);
            }
        });

        butt4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        butt4.setText("4");
        butt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt4ActionPerformed(evt);
            }
        });

        butt1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        butt1.setText("1");
        butt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt1ActionPerformed(evt);
            }
        });

        buttMod.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttMod.setText("%");
        buttMod.setEnabled(false);
        buttMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttModActionPerformed(evt);
            }
        });

        butt8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        butt8.setText("8");
        butt8.setEnabled(false);
        butt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt8ActionPerformed(evt);
            }
        });

        butt5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        butt5.setText("5");
        butt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt5ActionPerformed(evt);
            }
        });

        butt2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        butt2.setText("2");
        butt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt2ActionPerformed(evt);
            }
        });

        butt9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        butt9.setText("9");
        butt9.setEnabled(false);
        butt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt9ActionPerformed(evt);
            }
        });

        butt6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        butt6.setText("6");
        butt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt6ActionPerformed(evt);
            }
        });

        butt3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        butt3.setText("3");
        butt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt3ActionPerformed(evt);
            }
        });

        buttKurAwal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttKurAwal.setText("(");
        buttKurAwal.setEnabled(false);
        buttKurAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttKurAwalActionPerformed(evt);
            }
        });

        buttX.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttX.setText("X");
        buttX.setEnabled(false);

        butMin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        butMin.setText("-");
        butMin.setEnabled(false);
        butMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMinActionPerformed(evt);
            }
        });

        buttPlus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttPlus.setText("+");
        buttPlus.setEnabled(false);

        buttPoint.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttPoint.setText(".");
        buttPoint.setEnabled(false);
        buttPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttPointActionPerformed(evt);
            }
        });

        butt0.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        butt0.setText("0");
        butt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt0ActionPerformed(evt);
            }
        });

        buttEval.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttEval.setText("=");
        buttEval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttEvalActionPerformed(evt);
            }
        });

        buttKurAkhir.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttKurAkhir.setText(")");
        buttKurAkhir.setEnabled(false);
        buttKurAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttKurAkhirActionPerformed(evt);
            }
        });

        displayInnerBox.setEditable(false);
        displayInnerBox.setBackground(new java.awt.Color(204, 204, 204));
        displayInnerBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        displayInnerBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        displayInnerBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        displayInnerBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayInnerBoxActionPerformed(evt);
            }
        });

        buttMR.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttMR.setText("MR");
        buttMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttMRActionPerformed(evt);
            }
        });

        buttMC.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttMC.setText("MC");
        buttMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttMCActionPerformed(evt);
            }
        });

        buttMPlus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttMPlus.setText("M+");
        buttMPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttMPlusActionPerformed(evt);
            }
        });

        buttMMin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttMMin.setText("M-");
        buttMMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttMMinActionPerformed(evt);
            }
        });

        buttPlusOrMin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttPlusOrMin.setText("+/-");
        buttPlusOrMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttPlusOrMinActionPerformed(evt);
            }
        });

        buttDegRad.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttDegRad.setText("Deg");
        buttDegRad.setEnabled(false);
        buttDegRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttDegRadActionPerformed(evt);
            }
        });

        buttBagi.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttBagi.setText("/");
        buttBagi.setEnabled(false);

        buttPecahan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttPecahan.setText("1/x");
        buttPecahan.setEnabled(false);

        buttAkar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttAkar.setText("√x");
        buttAkar.setEnabled(false);
        buttAkar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttAkarActionPerformed(evt);
            }
        });

        buttFaktorial.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttFaktorial.setText("x!");
        buttFaktorial.setEnabled(false);

        buttPangkatY.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttPangkatY.setText("x^y");
        buttPangkatY.setEnabled(false);

        pilihanKonversi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Decimal to Binner", "Decimal to Oct", "Binner to Decimal", "Binner to Oct", "Oct to Decimal", "Oct to Binner" }));
        pilihanKonversi.setVerifyInputWhenFocusTarget(false);
        pilihanKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanKonversiActionPerformed(evt);
            }
        });

        jLabel1.setText("Pilihan Konversi :");

        buttSin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttSin.setText("Sin");
        buttSin.setEnabled(false);
        buttSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttSinActionPerformed(evt);
            }
        });

        buttCos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttCos.setText("Cos");
        buttCos.setEnabled(false);

        buttTan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttTan.setText("Tan");
        buttTan.setEnabled(false);

        butCosec.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        butCosec.setText("Cosec");
        butCosec.setEnabled(false);
        butCosec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCosecActionPerformed(evt);
            }
        });

        buttSec.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttSec.setText("Sec");
        buttSec.setEnabled(false);
        buttSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttSecActionPerformed(evt);
            }
        });

        buttCot.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttCot.setText("Cot");
        buttCot.setEnabled(false);
        buttCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttCotActionPerformed(evt);
            }
        });

        buttExp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttExp.setText("Exp");
        buttExp.setEnabled(false);
        buttExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttExpActionPerformed(evt);
            }
        });

        buttLog.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        buttLog.setText("log10");
        buttLog.setEnabled(false);
        buttLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttLogActionPerformed(evt);
            }
        });

        displayMemoryBox.setBackground(new java.awt.Color(180, 180, 180));
        displayMemoryBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        displayMemoryBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        displayMemoryBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayMemoryBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KalkulatorPanelLayout = new javax.swing.GroupLayout(KalkulatorPanel);
        KalkulatorPanel.setLayout(KalkulatorPanelLayout);
        KalkulatorPanelLayout.setHorizontalGroup(
            KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KalkulatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KalkulatorPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pilihanKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(displayBox)
                    .addComponent(displayInnerBox, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KalkulatorPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayMemoryBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KalkulatorPanelLayout.createSequentialGroup()
                                .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(KalkulatorPanelLayout.createSequentialGroup()
                                        .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(buttExp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(buttLog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(KalkulatorPanelLayout.createSequentialGroup()
                                                .addComponent(buttKurAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttKurAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttMod, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttX, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(KalkulatorPanelLayout.createSequentialGroup()
                                                .addComponent(buttMR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttMC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttMPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttMMin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(KalkulatorPanelLayout.createSequentialGroup()
                                        .addComponent(buttDegRad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(264, 264, 264))
                                    .addGroup(KalkulatorPanelLayout.createSequentialGroup()
                                        .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(buttPecahan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(buttAkar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(buttFaktorial, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(buttPangkatY, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(KalkulatorPanelLayout.createSequentialGroup()
                                                .addComponent(buttPlusOrMin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(butt0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(buttPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttEval, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(KalkulatorPanelLayout.createSequentialGroup()
                                                .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(butt7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(butt4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(butt1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(butt8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(butt5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(butt2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(butt9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(butt6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(butt3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(buttBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(butMin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(buttPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(buttCos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttCot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(buttTan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(butCosec, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(buttSec, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(buttSin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(buttC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        KalkulatorPanelLayout.setVerticalGroup(
            KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KalkulatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayInnerBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayMemoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihanKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttDegRad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KalkulatorPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buttMMin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttMPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttMC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttMR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttLog, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buttKurAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttKurAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttMod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttExp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(KalkulatorPanelLayout.createSequentialGroup()
                                .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(butt7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttPecahan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(butt4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttAkar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(butt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttFaktorial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(KalkulatorPanelLayout.createSequentialGroup()
                                    .addComponent(butt8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(butt5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(butt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(KalkulatorPanelLayout.createSequentialGroup()
                                    .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(butt9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(butt6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(butMin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(butt3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KalkulatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butt0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttPlusOrMin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttEval, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttPangkatY, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(KalkulatorPanelLayout.createSequentialGroup()
                        .addComponent(buttSin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttCos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttTan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butCosec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttSec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttCot, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuFile.setText("File");

        itemKalkulator.setText("Kalkulator");
        itemKalkulator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemKalkulatorActionPerformed(evt);
            }
        });
        menuFile.add(itemKalkulator);

        itemKonversi.setText("Konversi");
        itemKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemKonversiActionPerformed(evt);
            }
        });
        menuFile.add(itemKonversi);

        jMenuBar2.add(menuFile);

        menuAbout.setText("About");
        jMenuBar2.add(menuAbout);

        menuHelp.setText("Help");
        jMenuBar2.add(menuHelp);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(KalkulatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(KalkulatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemKonversiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemKonversiActionPerformed

    private void buttKurAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttKurAkhirActionPerformed
        // TODO add your handling code here:
        display     +=")";
        displayBox.setText(display);
    }//GEN-LAST:event_buttKurAkhirActionPerformed

    private void buttEvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttEvalActionPerformed
        // TODO add your handling code here:
        String hasil;
        int decimal;
        if(pilihanKonversi.getSelectedIndex() == 4){
            hasil = Integer.toString(octalConvert(Integer.parseInt(display)));
            displayBox.setText(hasil);
        } else if(pilihanKonversi.getSelectedIndex() == 5){
            decimal = octalConvert(Integer.parseInt(display));
            hasil = Integer.toBinaryString(decimal);
            displayBox.setText(hasil);
        }
    }//GEN-LAST:event_buttEvalActionPerformed

    private void butt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt0ActionPerformed
        // TODO add your handling code here
        
        display = display +"0";
        displayBox.setText(display);
        displayInnerBox.setText(display);
    }//GEN-LAST:event_butt0ActionPerformed

    private void buttPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttPointActionPerformed
        // TODO add your handling code here:
        display     +=".";
        displayBox.setText(display);
    }//GEN-LAST:event_buttPointActionPerformed

    private void buttKurAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttKurAwalActionPerformed
        // TODO add your handling code here:
        display     +="(";
        displayBox.setText(display);
    }//GEN-LAST:event_buttKurAwalActionPerformed

    private void butt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt3ActionPerformed
        // TODO add your handling code here
        display = display +"3";
        displayBox.setText(display);
        displayInnerBox.setText(display);
    }//GEN-LAST:event_butt3ActionPerformed

    private void butt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt6ActionPerformed
        // TODO add your handling code here:
        display = display +"6";
        displayBox.setText(display);
        displayInnerBox.setText(display);
    }//GEN-LAST:event_butt6ActionPerformed

    private void butt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt9ActionPerformed
        // TODO add your handling code here:
        display = display +"9";
        displayBox.setText(display);
        displayInnerBox.setText(display);
    }//GEN-LAST:event_butt9ActionPerformed

    private void butt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt2ActionPerformed
        // TODO add your handling code here:
        display = display +"2";
        displayBox.setText(display);
        displayInnerBox.setText(display);
    }//GEN-LAST:event_butt2ActionPerformed

    private void butt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt5ActionPerformed
        // TODO add your handling code here:
        display = display +"5";
        displayBox.setText(display);
        displayInnerBox.setText(display);
    }//GEN-LAST:event_butt5ActionPerformed

    private void butt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt8ActionPerformed
        // TODO add your handling code here
        display = display +"8";
        displayBox.setText(display);
        displayInnerBox.setText(display);
    }//GEN-LAST:event_butt8ActionPerformed

    private void buttModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttModActionPerformed
        // TODO add your handling code here:
        display     +="%";
        displayBox.setText(display);
    }//GEN-LAST:event_buttModActionPerformed

    private void butt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt1ActionPerformed
        // TODO add your handling code here
        display     +="1";
        displayBox.setText(display);
        displayInnerBox.setText(display);
    }//GEN-LAST:event_butt1ActionPerformed

    private void butt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt4ActionPerformed
        // TODO add your handling code here
        display = display +"4";
        displayBox.setText(display);
        displayInnerBox.setText(display);
    }//GEN-LAST:event_butt4ActionPerformed

    private void butt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt7ActionPerformed
        // TODO add your handling code here:
        display = display +"7";
        displayBox.setText(display);
        displayInnerBox.setText(display);
    }//GEN-LAST:event_butt7ActionPerformed

    private void buttCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttCActionPerformed
        // TODO add your handling code here:
        display = "";
        displayBox.setText(display);
        displayInnerBox.setText(display);
    }//GEN-LAST:event_buttCActionPerformed

    private void displayBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayBoxActionPerformed

    private void displayInnerBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayInnerBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayInnerBoxActionPerformed

    private void buttMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttMRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttMRActionPerformed

    private void buttMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttMCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttMCActionPerformed

    private void buttMPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttMPlusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttMPlusActionPerformed

    private void buttMMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttMMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttMMinActionPerformed

    private void buttPlusOrMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttPlusOrMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttPlusOrMinActionPerformed

    private void butMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butMinActionPerformed

    private void buttDegRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttDegRadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttDegRadActionPerformed

    private void buttAkarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttAkarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttAkarActionPerformed

    private void itemKalkulatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemKalkulatorActionPerformed
        // TODO add your handling code here:
        KalkulatorUtama ku = new KalkulatorUtama("Kalkulator");
        ku.show();
        dispose();
    }//GEN-LAST:event_itemKalkulatorActionPerformed

    private void pilihanKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanKonversiActionPerformed
        // TODO add your handling code here:
        KalkulatorKonversiDecimal knd = new KalkulatorKonversiDecimal("Konversi");
        KalkulatorKonversiBinner knb = new KalkulatorKonversiBinner("Konversi");
        switch(pilihanKonversi.getSelectedIndex()){
            case 0 -> {
                knd.pilihanKonversi.setSelectedIndex(0);
                knd.displayBox.setText("");
                knd.displayInnerBox.setText("");
                knd.show();
                dispose();
            }
            case 1 -> {
                knd.pilihanKonversi.setSelectedIndex(1);
                knd.displayBox.setText("");
                knd.displayInnerBox.setText("");
                knd.show();
                dispose();
            }
            case 2 -> {
                knb.pilihanKonversi.setSelectedIndex(2);
                knb.displayBox.setText("");
                knb.displayInnerBox.setText("");
                knb.show();
                dispose();
            }
            case 3 -> {
                knb.pilihanKonversi.setSelectedIndex(3);
                knb.displayBox.setText("");
                knb.displayInnerBox.setText("");
                knb.show();
                dispose();
            }
            case 4 -> {
                display = "";
                displayBox.setText(display);
                displayInnerBox.setText(display);
                break;
            }
            case 5 -> {
                display = "";
                displayBox.setText(display);
                displayInnerBox.setText(display);
                break;
            }
        }
    }//GEN-LAST:event_pilihanKonversiActionPerformed

    private void buttSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttSinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttSinActionPerformed

    private void butCosecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCosecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butCosecActionPerformed

    private void buttCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttCotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttCotActionPerformed

    private void buttSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttSecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttSecActionPerformed

    private void buttExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttExpActionPerformed

    private void buttLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttLogActionPerformed

    private void displayMemoryBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayMemoryBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayMemoryBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorKonversiOct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorKonversiOct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorKonversiOct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorKonversiOct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorKonversiOct("Konversi").setVisible(true);
            }
        });
    }
    
    private static int octalConvert(int octal) {
        int decimalResult = 0,i=0;
        while(octal != 0){
            decimalResult += (octal % 10) * Math.pow(8, i);
            ++i;
            octal /= 10;
        }
        return decimalResult;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel KalkulatorPanel;
    private javax.swing.JButton butCosec;
    private javax.swing.JButton butMin;
    private javax.swing.JButton butt0;
    private javax.swing.JButton butt1;
    private javax.swing.JButton butt2;
    private javax.swing.JButton butt3;
    private javax.swing.JButton butt4;
    private javax.swing.JButton butt5;
    private javax.swing.JButton butt6;
    private javax.swing.JButton butt7;
    private javax.swing.JButton butt8;
    private javax.swing.JButton butt9;
    private javax.swing.JButton buttAkar;
    private javax.swing.JButton buttBagi;
    private javax.swing.JButton buttC;
    private javax.swing.JButton buttCos;
    private javax.swing.JButton buttCot;
    private javax.swing.JButton buttDegRad;
    private javax.swing.JButton buttEval;
    private javax.swing.JButton buttExp;
    private javax.swing.JButton buttFaktorial;
    private javax.swing.JButton buttKurAkhir;
    private javax.swing.JButton buttKurAwal;
    private javax.swing.JButton buttLog;
    private javax.swing.JButton buttMC;
    private javax.swing.JButton buttMMin;
    private javax.swing.JButton buttMPlus;
    private javax.swing.JButton buttMR;
    private javax.swing.JButton buttMod;
    private javax.swing.JButton buttPangkatY;
    private javax.swing.JButton buttPecahan;
    private javax.swing.JButton buttPlus;
    private javax.swing.JButton buttPlusOrMin;
    private javax.swing.JButton buttPoint;
    private javax.swing.JButton buttSec;
    private javax.swing.JButton buttSin;
    private javax.swing.JButton buttTan;
    private javax.swing.JButton buttX;
    protected javax.swing.JTextField displayBox;
    protected javax.swing.JTextField displayInnerBox;
    private javax.swing.JTextField displayMemoryBox;
    private javax.swing.JMenuItem itemKalkulator;
    private javax.swing.JMenuItem itemKonversi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    protected javax.swing.JComboBox<String> pilihanKonversi;
    // End of variables declaration//GEN-END:variables
}
